# https://docs.sqlc.dev/en/stable/reference/config.html
version: "2"
sql:
  - schema: "../../pkg/sqlc/migrations" # マイグレーションのディレクトリ OR 単一のSQLファイルへのパス OR パスのリスト
    queries: "../../pkg/sqlc/queries" # SQLクエリのディレクトリ OR 単一のSQLファイルへのパス OR パスのリスト
    engine: "mysql" # or postgresql
    gen:
      go:
        package: "sqlc"
        out: "../../pkg/sqlc/"
        emit_interface: true
        emit_empty_slices: true # 空のsliceをnilではなく空に
        emit_exported_queries: false # 出力するクエリをexportする
        emit_json_tags: true # jsonタグを追加する
        emit_exact_table_names: false # accounts table -> Account struct
