version: "3.9"
services:
  mysql:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=simplebank
      - MYSQL_ROOT_HOST=%
    command:
      - --character-set-server=utf8mb4
      - --sql-mode=ONLY_FULL_GROUP_BY,NO_ENGINE_SUBSTITUTION
  api:
    build:
      context: .  # root directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=root:example@tcp(mysql:3306)/simplebank?parseTime=true
    depends_on:
      - mysql
    entrypoint:
      [
        "/app/wait-for.sh",
        "mysql:3306",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]