// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: transfers.sql

package internal

import (
	"context"
)

const createTransfer = `-- name: CreateTransfer :execlastid
INSERT INTO transfers (
  from_wallet_id,
  to_wallet_id,
  amount
) VALUES (
  ?, ?, ?
)
`

type CreateTransferParams struct {
	FromWalletID int64 `json:"from_wallet_id"`
	ToWalletID   int64 `json:"to_wallet_id"`
	Amount       int64 `json:"amount"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTransfer, arg.FromWalletID, arg.ToWalletID, arg.Amount)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, from_wallet_id, to_wallet_id, amount, created_at FROM transfers
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTransfer(ctx context.Context, id int64) (*Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.CreatedAt,
	)
	return &i, err
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, from_wallet_id, to_wallet_id, amount, created_at FROM transfers
ORDER BY id
LIMIT ?
OFFSET ?
`

type ListTransfersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]*Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromWalletID,
			&i.ToWalletID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
