name: sqlc-ci

on:
  push:
    branches: [main]
    paths:
      - "sqlc/**"
  pull_request:
    branches: [main]
    paths:
      - "sqlc/**"

jobs:
  build:
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: sqlc
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Create tmp directory
        run: |
          mkdir -p ./bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Install golang-migrate v4.15.0
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.0/migrate.linux-amd64.tar.gz | tar xvz -C ./bin

      - name: Run migrations
        run: make db/migrate
        working-directory: ./sqlc

      - name: Test
        run: go test -v ./...
        working-directory: ./sqlc
